
# Site settings
title: nick normandin
email: nicholas.e.normandin@gmail.com
description: science, books, adventure
baseurl: "" # the subpath of your site, e.g. /blog
url: "nnormandin.com" # the base hostname & protocol for your site

github_username:  nnormandin
twitter_username:
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: redcarpet
