
# Site settings
title: Nick Normandin
email: nicholas.e.normandin@gmail.com
description: just a fun guy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nnormandin.github.io" # the base hostname & protocol for your site

github_username:  nnormandin
twitter_username:
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
